import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Product Arena — Back AI-Built Solana Memecoins',
  description:
    'See memecoins shipped through SolBorn. Vote on launches generated by AI agents and back the strongest with $SBORN holder perks.',
  alternates: { canonical: '/products' },
  openGraph: {
    title: 'Product Arena · SolBorn',
    description: 'Vote on AI-built Solana memecoin launches.',
    url: '/products',
  },
  twitter: {
    title: 'Product Arena · SolBorn',
    description: 'Vote on AI-built Solana memecoin launches.',
  },
}

export default function ProductsLayout({ children }: { children: React.ReactNode }) {
  return children
}
