'use client'

import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { ArrowLeft, Check, ExternalLink, Loader2, Lock, Rocket, Send, ShieldCheck } from 'lucide-react'
import { useWallet } from '@solana/wallet-adapter-react'
import { Button } from '@/components/ui/button'
import { WalletButton } from '@/components/wallet/WalletButton'
import { useForgeStore } from '@/lib/store'
import type { GeneratedProject } from '@/lib/types'

function shortHash(hash: string): string {
  return `${hash.slice(0, 8)}...${hash.slice(-8)}`
}

export default function ProductPage() {
  const router = useRouter()
  const params = useParams<{ id: string }>()
  const agents = useForgeStore((s) => s.agents)
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
  }, [])

  const productId = String(params?.id ?? '')
  const match = useMemo(
    () => agents.find((agent) => agent.generatedProject?.id === productId),
    [agents, productId],
  )
  const agent = match ?? null
  const project = match?.generatedProject ?? null

  return (
    <main className="min-h-screen px-6 py-6">
      <div className="max-w-6xl mx-auto">
        <header className="flex items-center gap-3 mb-8 flex-wrap">
          <Button variant="ghost" size="sm" onClick={() => router.push('/')}>
            <ArrowLeft size={16} />
          </Button>
          <img
            src="/logo.png"
            alt="SolBorn"
            className="w-8 h-8 rounded-xl cursor-pointer"
            onClick={() => router.push('/')}
          />
          <div className="flex-1 min-w-44">
            <h1 className="text-2xl font-bold text-zinc-100">SolBorn Product Page</h1>
            <p className="text-sm text-zinc-500">Generated by a trained founder agent</p>
          </div>
          <Button variant="secondary" size="sm" onClick={() => router.push('/staking')}>
            $SBORN access
          </Button>
          <Button variant="secondary" size="sm" onClick={() => router.push('/products')}>
            Arena
          </Button>
        </header>

        {!mounted ? (
          <EmptyState title="Loading product..." body="Reading your local SolBorn launch data." />
        ) : !project || !agent ? (
          <EmptyState
            title="Product not found in this browser"
            body="This v1 page reads the product generated by your local agent. Generate a project from an Adult agent first, then open its Product Page link."
          />
        ) : (
          <ProductContent project={project} agentName={agent.name} agentStage={agent.stage} />
        )}
      </div>
    </main>
  )
}

function ProductContent({
  project,
  agentName,
  agentStage,
}: {
  project: GeneratedProject
  agentName: string
  agentStage: string
}) {
  const { publicKey } = useWallet()
  const brief = project.brief
  const membership = project.membership
  const [contact, setContact] = useState('')
  const [note, setNote] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [result, setResult] = useState<{ ok: boolean; message: string } | null>(null)

  async function submitInterest(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    if (!contact.trim() || submitting) return
    setSubmitting(true)
    setResult(null)
    try {
      const res = await fetch('/api/products/interest', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          productId: project.id,
          productName: project.name,
          agentName,
          contact: contact.trim(),
          note: note.trim(),
          wallet: publicKey?.toBase58() ?? null,
        }),
      })
      const data = (await res.json()) as { ok?: boolean; message?: string; error?: string }
      if (!res.ok || !data.ok) {
        throw new Error(data.error ?? 'Request failed')
      }
      setResult({ ok: true, message: data.message ?? 'Request received.' })
      setContact('')
      setNote('')
    } catch (error) {
      setResult({
        ok: false,
        message: error instanceof Error ? error.message : 'Request failed',
      })
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="space-y-5">
      <section className="grid lg:grid-cols-[1.15fr_0.85fr] gap-5 items-stretch">
        <div className="glass p-7 border border-white/10 relative overflow-hidden">
          <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-emerald-300/50 to-transparent" />
          <div className="inline-flex items-center px-3 py-1 rounded-full border border-emerald-300/25 bg-emerald-300/10 text-[11px] font-semibold text-emerald-200 mb-5">
            Agent-built product
          </div>
          <h2 className="text-4xl sm:text-5xl font-bold tracking-tight text-zinc-100 mb-4">
            {project.name}
          </h2>
          <p className="text-zinc-400 leading-relaxed max-w-3xl">
            {project.description}
          </p>
          <div className="flex flex-wrap gap-2 mt-6">
            {project.techStack.map((tech) => (
              <span
                key={tech}
                className="text-xs px-2.5 py-1 rounded-md bg-white/5 border border-white/10 text-zinc-400"
              >
                {tech}
              </span>
            ))}
          </div>
        </div>

        <div className="glass p-6 border border-white/10">
          <div className="flex items-center gap-2 mb-5">
            <Rocket size={17} className="text-amber-300" />
            <h3 className="text-sm font-semibold text-zinc-100">Launch status</h3>
          </div>
          <div className="space-y-3">
            <StatusLine label="Founder agent" value={agentName} />
            <StatusLine label="Stage" value={agentStage} />
            <StatusLine label="Product page" value="Ready" />
            <StatusLine label="Network" value="Solana devnet" />
          </div>
          {project.txHash ? (
            <a
              href={`https://explorer.solana.com/tx/${project.txHash}?cluster=devnet`}
              target="_blank"
              rel="noopener noreferrer"
              className="mt-5 flex items-center justify-center gap-1.5 rounded-lg px-3 py-2 text-xs font-medium bg-emerald-300 text-zinc-950 hover:bg-emerald-200 transition-colors"
            >
              <ExternalLink size={12} />
              View certificate {shortHash(project.txHash)}
            </a>
          ) : (
            <div className="mt-5 rounded-lg border border-amber-300/20 bg-amber-300/10 px-3 py-2 text-xs text-amber-100">
              Publish the Launch Certificate to attach on-chain proof.
            </div>
          )}
        </div>
      </section>

      <section className="grid lg:grid-cols-[0.92fr_1.08fr] gap-5">
        <div className="glass p-6 border border-white/10">
          <div className="flex items-center gap-2 mb-5">
            <Lock size={17} className="text-violet-300" />
            <h3 className="text-sm font-semibold text-zinc-100">Membership Pass</h3>
          </div>
          <h4 className="text-2xl font-bold text-zinc-100">
            {membership?.title ?? `${project.name} Access Pass`}
          </h4>
          <p className="text-sm text-zinc-500 mt-2">
            ${membership?.priceUsd ?? 9} for {membership?.durationDays ?? 30} days of early access.
          </p>
          <div className="space-y-2 mt-5">
            {(membership?.benefits ?? ['Early product access', 'Founder updates', 'Priority feedback loop']).map((benefit, index) => (
              <div
                key={benefit}
                className="flex items-start gap-3 rounded-lg border border-white/10 bg-white/[0.03] px-3 py-2 text-sm text-zinc-300"
              >
                <span className="text-[10px] font-bold text-violet-300 mt-0.5">{index + 1}</span>
                <span>{benefit}</span>
              </div>
            ))}
          </div>
          <Button disabled className="w-full mt-5 bg-violet-400 text-zinc-950 opacity-70">
            Pass checkout soon
          </Button>

          <form onSubmit={submitInterest} className="mt-5 space-y-3 border-t border-white/10 pt-5">
            <div className="flex items-center justify-between gap-3">
              <div>
                <p className="text-xs font-semibold uppercase tracking-wider text-zinc-500">
                  Request access
                </p>
                <p className="text-xs text-zinc-600 mt-1">Capture early users before checkout is live.</p>
              </div>
              <WalletButton />
            </div>
            <input
              value={contact}
              onChange={(event) => setContact(event.target.value)}
              placeholder="X / Telegram / email"
              className="w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-zinc-100 placeholder:text-zinc-700 focus:outline-none focus:border-violet-300/60"
              maxLength={120}
            />
            <textarea
              value={note}
              onChange={(event) => setNote(event.target.value)}
              placeholder="What do you want access for?"
              className="min-h-20 w-full resize-none rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-zinc-100 placeholder:text-zinc-700 focus:outline-none focus:border-violet-300/60"
              maxLength={500}
            />
            <Button
              type="submit"
              disabled={!contact.trim() || submitting}
              className="w-full bg-white text-zinc-950 hover:bg-zinc-200"
            >
              {submitting ? <Loader2 size={15} className="animate-spin" /> : result?.ok ? <Check size={15} /> : <Send size={15} />}
              {submitting ? 'Sending...' : result?.ok ? 'Request sent' : 'Request early access'}
            </Button>
            {result && (
              <p className={`text-xs leading-relaxed ${result.ok ? 'text-emerald-300' : 'text-rose-300'}`}>
                {result.message}
              </p>
            )}
          </form>
        </div>

        <div className="glass p-6 border border-white/10">
          <div className="flex items-center gap-2 mb-5">
            <ShieldCheck size={17} className="text-emerald-300" />
            <h3 className="text-sm font-semibold text-zinc-100">Product Brief</h3>
          </div>
          <div className="grid sm:grid-cols-2 gap-3">
            <BriefBlock label="Target user" value={brief?.targetUser} />
            <BriefBlock label="Problem" value={brief?.problem} />
            <BriefBlock label="Solution" value={brief?.solution} />
            <BriefBlock label="MVP" value={brief?.mvp} />
            <BriefBlock label="Solana angle" value={brief?.solanaAngle} />
            <BriefBlock label="Pricing" value={brief?.pricing} />
          </div>
          <div className="mt-5">
            <p className="text-xs font-semibold uppercase tracking-wider text-zinc-500 mb-3">
              Launch plan
            </p>
            <div className="space-y-2">
              {(brief?.launchPlan ?? ['Generate product page', 'Publish certificate', 'Invite early users']).map((step, index) => (
                <div
                  key={step}
                  className="flex items-start gap-3 rounded-lg border border-white/10 bg-white/[0.03] px-3 py-2 text-sm text-zinc-300"
                >
                  <span className="text-[10px] font-bold text-emerald-300 mt-0.5">{index + 1}</span>
                  <span>{step}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}

function BriefBlock({ label, value }: { label: string; value?: string }) {
  return (
    <div className="rounded-lg border border-white/10 bg-white/[0.03] p-4">
      <p className="text-[10px] uppercase tracking-wider text-zinc-600">{label}</p>
      <p className="text-sm text-zinc-300 leading-relaxed mt-2">{value ?? 'Defined by the founder agent during generation.'}</p>
    </div>
  )
}

function StatusLine({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between gap-3 rounded-lg border border-white/10 bg-white/[0.03] px-3 py-2">
      <span className="text-xs text-zinc-600">{label}</span>
      <span className="text-xs text-zinc-200 text-right capitalize">{value}</span>
    </div>
  )
}

function EmptyState({ title, body }: { title: string; body: string }) {
  const router = useRouter()
  return (
    <div className="glass p-8 border border-white/10 text-center max-w-xl mx-auto">
      <h2 className="text-2xl font-bold text-zinc-100">{title}</h2>
      <p className="text-sm text-zinc-500 leading-relaxed mt-3">{body}</p>
      <Button onClick={() => router.push('/')} className="mt-6">
        Back to SolBorn
      </Button>
    </div>
  )
}
