'use client'

import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { ArrowLeft, Check, ExternalLink, Loader2, Lock, MessageCircle, Rocket, Send, Share2, ShieldCheck, Sparkles } from 'lucide-react'
import { useSolanaSigner } from '@/lib/hooks/useSolanaSigner'
import { Button } from '@/components/ui/button'
import { WalletButton } from '@/components/wallet/WalletButton'
import { useForgeStore } from '@/lib/store'
import type { ForgeAgent, GeneratedProject } from '@/lib/types'

function shortHash(hash: string): string {
  return `${hash.slice(0, 8)}...${hash.slice(-8)}`
}

export default function ProductPage() {
  const router = useRouter()
  const params = useParams<{ id: string }>()
  const agents = useForgeStore((s) => s.agents)
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
  }, [])

  const productId = String(params?.id ?? '')
  const match = useMemo(
    () => agents.find((agent) => agent.generatedProject?.id === productId),
    [agents, productId],
  )
  const agent = match ?? null
  const project = match?.generatedProject ?? null

  return (
    <main className="min-h-screen px-6 py-6">
      <div className="max-w-6xl mx-auto">
        <header className="flex items-center gap-3 mb-8 flex-wrap">
          <Button variant="ghost" size="sm" onClick={() => router.push('/')}>
            <ArrowLeft size={16} />
          </Button>
          <img
            src="/logo.png"
            alt="SolBorn"
            className="w-8 h-8 rounded-xl cursor-pointer"
            onClick={() => router.push('/')}
          />
          <div className="flex-1 min-w-44">
            <h1 className="text-2xl font-bold text-zinc-100">SolBorn Product Page</h1>
            <p className="text-sm text-zinc-500">Generated from a founder interview</p>
          </div>
          <Button variant="secondary" size="sm" onClick={() => router.push('/staking')}>
            $SBORN access
          </Button>
          <Button variant="secondary" size="sm" onClick={() => router.push('/products')}>
            Arena
          </Button>
        </header>

        {!mounted ? (
          <EmptyState title="Loading product..." body="Reading your local SolBorn launch data." />
        ) : !project || !agent ? (
          <EmptyState
            title="Product not found in this browser"
            body="This v1 page reads the product generated by your local agent. Generate a project from an Adult agent first, then open its Product Page link."
          />
        ) : (
          <ProductContent project={project} agent={agent} />
        )}
      </div>
    </main>
  )
}

function ProductContent({
  project,
  agent,
}: {
  project: GeneratedProject
  agent: ForgeAgent
}) {
  const { publicKey } = useSolanaSigner()
  const brief = project.brief
  const agentName = agent.name
  const agentStage = agent.stage
  const [contact, setContact] = useState('')
  const [useCase, setUseCase] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [result, setResult] = useState<{ ok: boolean; message: string } | null>(null)
  const canSubmit = contact.trim().length >= 3 && useCase.trim().length >= 20

  const artworkUrl = useMemo(() => {
    const params = new URLSearchParams({
      kind: 'launch',
      id: agent.id,
      n: agent.name,
      s: agent.stage,
      p: agent.personality,
      xp: String(agent.xp),
      proj: project.name,
      pid: project.id,
    })
    return `/api/nft-metadata/og?${params.toString()}`
  }, [agent.id, agent.name, agent.stage, agent.personality, agent.xp, project.name, project.id])

  const shareUrl = useMemo(() => {
    const text = `${project.name} — built by an AI co-founder on @solborn_xyz. Solana devnet launch certificate attached.`
    const pageUrl = typeof window !== 'undefined'
      ? window.location.href
      : `https://solborn.xyz/products/${project.id}`
    const params = new URLSearchParams({ text, url: pageUrl })
    return `https://twitter.com/intent/tweet?${params.toString()}`
  }, [project.name, project.id])

  const interviewBubbles = useMemo(() => {
    return agent.messages.filter((m) => m.role !== 'system').slice(-3)
  }, [agent.messages])

  function scrollToRequestAccess() {
    document.getElementById('request-access')?.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }

  async function submitInterest(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    if (!canSubmit || submitting) return
    setSubmitting(true)
    setResult(null)
    try {
      const res = await fetch('/api/products/interest', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          productId: project.id,
          productName: project.name,
          agentName,
          contact: contact.trim(),
          useCase: useCase.trim(),
          wallet: publicKey?.toBase58() ?? null,
        }),
      })
      const data = (await res.json()) as { ok?: boolean; message?: string; error?: string }
      if (!res.ok || !data.ok) {
        throw new Error(data.error ?? 'Request failed')
      }
      setResult({ ok: true, message: data.message ?? 'Request received.' })
      setContact('')
      setUseCase('')
    } catch (error) {
      setResult({
        ok: false,
        message: error instanceof Error ? error.message : 'Request failed',
      })
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="space-y-5">
      <section className="grid lg:grid-cols-[1.15fr_0.85fr] gap-5 items-start">
        <div className="glass p-7 border border-white/10 relative overflow-hidden">
          <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-emerald-300/50 to-transparent" />
          <div className="inline-flex items-center px-3 py-1 rounded-full border border-emerald-300/25 bg-emerald-300/10 text-[11px] font-semibold text-emerald-200 mb-5">
            Agent-built product
          </div>
          <h2 className="text-4xl sm:text-5xl font-bold tracking-tight text-zinc-100 mb-3">
            {project.name}
          </h2>
          {project.tagline && (
            <p className="text-lg sm:text-xl text-zinc-200 leading-snug max-w-3xl mb-4">
              {project.tagline}
            </p>
          )}
          <p className="text-zinc-400 leading-relaxed max-w-3xl">
            {project.description}
          </p>
          <div className="flex flex-wrap gap-2 mt-5">
            <button
              onClick={scrollToRequestAccess}
              className="inline-flex items-center gap-2 rounded-xl bg-violet-500 px-4 py-2 text-sm font-semibold text-white hover:bg-violet-400 transition-colors"
            >
              Request beta access
            </button>
            {project.txHash && (
              <a
                href={`https://explorer.solana.com/tx/${project.txHash}?cluster=devnet`}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.03] px-4 py-2 text-sm font-semibold text-zinc-200 hover:bg-white/[0.06] transition-colors"
              >
                <ExternalLink size={14} />
                View launch proof
              </a>
            )}
            <a
              href={shareUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.03] px-4 py-2 text-sm font-semibold text-zinc-200 hover:bg-white/[0.06] transition-colors"
            >
              <Share2 size={14} />
              Share on X
            </a>
          </div>
          <div className="flex flex-wrap gap-2 mt-6">
            {project.techStack.map((tech) => (
              <span
                key={tech}
                className="text-xs px-2.5 py-1 rounded-md bg-white/5 border border-white/10 text-zinc-400"
              >
                {tech}
              </span>
            ))}
          </div>
        </div>

        <div className="glass p-6 border border-white/10">
          <div className="flex items-center gap-2 mb-5">
            <Rocket size={17} className="text-amber-300" />
            <h3 className="text-sm font-semibold text-zinc-100">Launch status</h3>
          </div>
          <div className="relative aspect-square w-full overflow-hidden rounded-xl border border-white/10 bg-black/30 mb-5">
            <img
              src={artworkUrl}
              alt={`${project.name} Launch Certificate`}
              className="absolute inset-0 h-full w-full object-cover"
              loading="lazy"
            />
            <div className="absolute bottom-2 left-2 inline-flex items-center gap-1 rounded-md border border-white/10 bg-black/60 px-2 py-1 text-[10px] font-mono uppercase tracking-wider text-zinc-300 backdrop-blur">
              <ShieldCheck size={10} className="text-emerald-300" />
              Launch Certificate
            </div>
          </div>
          <div className="space-y-3">
            <StatusLine label="Founder agent" value={agentName} />
            <StatusLine label="Stage" value={agentStage} />
            <StatusLine label="Product page" value="Ready" />
            <StatusLine label="Network" value="Solana devnet" />
          </div>
          <div className="grid grid-cols-2 gap-2 mt-5">
            <MiniSignal label="Proof" value={project.txHash ? 'Live' : 'Pending'} />
            <MiniSignal label="Access" value="Waitlist" />
          </div>
          {project.txHash ? (
            <a
              href={`https://explorer.solana.com/tx/${project.txHash}?cluster=devnet`}
              target="_blank"
              rel="noopener noreferrer"
              className="mt-5 flex items-center justify-center gap-1.5 rounded-lg px-3 py-2 text-xs font-medium bg-emerald-300 text-zinc-950 hover:bg-emerald-200 transition-colors"
            >
              <ExternalLink size={12} />
              View certificate {shortHash(project.txHash)}
            </a>
          ) : (
            <div className="mt-5 rounded-lg border border-amber-300/20 bg-amber-300/10 px-3 py-2 text-xs text-amber-100">
              Publish the Launch Certificate to attach on-chain proof.
            </div>
          )}
        </div>
      </section>

      <section className="grid lg:grid-cols-[0.92fr_1.08fr] gap-5">
        <AgentIdCard agent={agent} />
        <InterviewExcerpt agent={agent} bubbles={interviewBubbles} />
      </section>

      <section className="grid lg:grid-cols-[0.92fr_1.08fr] gap-5">
        <div className="glass p-6 border border-white/10">
          <div className="flex items-center gap-2 mb-5">
            <Lock size={17} className="text-violet-300" />
            <h3 className="text-sm font-semibold text-zinc-100">Beta Access</h3>
          </div>
          <h4 className="text-2xl font-bold text-zinc-100">
            Get on the early access list
          </h4>
          <p className="text-sm text-zinc-500 mt-2">
            Free during the build phase. Tell us how you&apos;d use it — we hand-pick first users.
          </p>

          <div className="mt-5 space-y-2 rounded-xl border border-violet-300/15 bg-violet-400/[0.04] p-4">
            <p className="text-xs font-semibold uppercase tracking-wider text-violet-200">
              What happens next
            </p>
            <div className="space-y-2 text-sm text-zinc-300">
              <StepRow index="01" text="You send a serious beta request with your use case." />
              <StepRow index="02" text="We review fit manually instead of blasting open access." />
              <StepRow index="03" text="If it matches, the founder reaches out directly on your contact." />
            </div>
          </div>

          <form id="request-access" onSubmit={submitInterest} className="mt-5 space-y-3 border-t border-white/10 pt-5">
            <div className="flex items-center justify-between gap-3">
              <div>
                <p className="text-xs font-semibold uppercase tracking-wider text-zinc-500">
                  Request beta access
                </p>
                <p className="text-xs text-zinc-600 mt-1">Tell us how you would use it. We want real early users, not vanity signups.</p>
              </div>
              <WalletButton />
            </div>
            <input
              value={contact}
              onChange={(event) => setContact(event.target.value)}
              placeholder="X / Telegram / email"
              className="w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-zinc-100 placeholder:text-zinc-700 focus:outline-none focus:border-violet-300/60"
              maxLength={120}
            />
            <textarea
              value={useCase}
              onChange={(event) => setUseCase(event.target.value)}
              placeholder="What are you building, and how would you use this product? Be specific."
              className="min-h-24 w-full resize-none rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-zinc-100 placeholder:text-zinc-700 focus:outline-none focus:border-violet-300/60"
              maxLength={700}
            />
            <p className="text-[10px] text-zinc-600">{useCase.length}/700 · min 20 chars</p>
            <Button
              type="submit"
              disabled={!canSubmit || submitting}
              className="w-full bg-white text-zinc-950 hover:bg-zinc-200"
            >
              {submitting ? <Loader2 size={15} className="animate-spin" /> : result?.ok ? <Check size={15} /> : <Send size={15} />}
              {submitting ? 'Sending...' : result?.ok ? 'Request sent' : 'Request beta access'}
            </Button>
            {result && (
              <p className={`text-xs leading-relaxed ${result.ok ? 'text-emerald-300' : 'text-rose-300'}`}>
                {result.message}
              </p>
            )}
          </form>
        </div>

        <div className="glass p-6 border border-white/10">
          <div className="flex items-center gap-2 mb-5">
            <ShieldCheck size={17} className="text-emerald-300" />
            <h3 className="text-sm font-semibold text-zinc-100">Product Brief</h3>
          </div>
          <div className="grid sm:grid-cols-2 gap-3">
            <BriefBlock label="Target user" value={brief?.targetUser} />
            <BriefBlock label="Problem" value={brief?.problem} />
            <BriefBlock label="Solution" value={brief?.solution} />
            <BriefBlock label="MVP" value={brief?.mvp} />
            <BriefBlock label="Solana angle" value={brief?.solanaAngle} />
            <BriefBlock label="Pricing" value={brief?.pricing} />
          </div>
          <div className="mt-5">
            <p className="text-xs font-semibold uppercase tracking-wider text-zinc-500 mb-3">
              Launch plan
            </p>
            <div className="space-y-2">
              {(brief?.launchPlan ?? ['Generate product page', 'Publish certificate', 'Invite early users']).map((step, index) => (
                <div
                  key={step}
                  className="flex items-start gap-3 rounded-lg border border-white/10 bg-white/[0.03] px-3 py-2 text-sm text-zinc-300"
                >
                  <span className="text-[10px] font-bold text-emerald-300 mt-0.5">{index + 1}</span>
                  <span>{step}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}

function MiniSignal({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-white/10 bg-white/[0.03] px-3 py-2">
      <p className="text-[10px] uppercase tracking-wider text-zinc-600">{label}</p>
      <p className="text-sm font-semibold text-zinc-100 mt-1">{value}</p>
    </div>
  )
}

function StepRow({ index, text }: { index: string; text: string }) {
  return (
    <div className="flex items-start gap-3 rounded-lg border border-white/10 bg-black/20 px-3 py-2">
      <span className="mt-0.5 text-[10px] font-mono text-violet-300">{index}</span>
      <span>{text}</span>
    </div>
  )
}

function BriefBlock({ label, value }: { label: string; value?: string }) {
  return (
    <div className="rounded-lg border border-white/10 bg-white/[0.03] p-4">
      <p className="text-[10px] uppercase tracking-wider text-zinc-600">{label}</p>
      <p className="text-sm text-zinc-300 leading-relaxed mt-2">{value ?? 'Defined by the founder agent during generation.'}</p>
    </div>
  )
}

function StatusLine({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between gap-3 rounded-lg border border-white/10 bg-white/[0.03] px-3 py-2">
      <span className="text-xs text-zinc-600">{label}</span>
      <span className="text-xs text-zinc-200 text-right capitalize">{value}</span>
    </div>
  )
}

function AgentIdCard({ agent }: { agent: ForgeAgent }) {
  const xpPct = Math.min(100, Math.round((agent.xp / Math.max(1, agent.xp + agent.xpToNext)) * 100))
  return (
    <div className="glass p-6 border border-white/10">
      <div className="flex items-center gap-2 mb-5">
        <Sparkles size={17} className="text-violet-300" />
        <h3 className="text-sm font-semibold text-zinc-100">Founder Agent</h3>
      </div>
      <div className="flex items-center gap-4">
        <div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl border border-white/10 bg-gradient-to-br from-violet-500/20 to-emerald-300/10 text-4xl">
          {agent.emoji}
        </div>
        <div className="min-w-0">
          <p className="truncate text-lg font-bold text-zinc-100">{agent.name}</p>
          <p className="text-xs text-zinc-500 capitalize">{agent.stage} · {agent.personality}</p>
        </div>
      </div>
      <div className="mt-5 space-y-2">
        <div className="flex items-center justify-between text-[11px]">
          <span className="uppercase tracking-wider text-zinc-600">XP</span>
          <span className="font-mono text-zinc-300">{agent.xp.toLocaleString()}</span>
        </div>
        <div className="h-1.5 w-full overflow-hidden rounded-full bg-white/5">
          <div
            className="h-full rounded-full bg-gradient-to-r from-violet-400 to-emerald-300"
            style={{ width: `${xpPct}%` }}
          />
        </div>
      </div>
      <a
        href={`/forge/${agent.id}`}
        className="mt-5 inline-flex items-center gap-1.5 text-xs font-semibold text-violet-300 hover:text-violet-200 transition-colors"
      >
        Open agent <ExternalLink size={11} />
      </a>
    </div>
  )
}

function InterviewExcerpt({
  agent,
  bubbles,
}: {
  agent: ForgeAgent
  bubbles: ForgeAgent['messages']
}) {
  return (
    <div className="glass p-6 border border-white/10">
      <div className="flex items-center gap-2 mb-5">
        <MessageCircle size={17} className="text-emerald-300" />
        <h3 className="text-sm font-semibold text-zinc-100">Interview excerpt</h3>
      </div>
      {bubbles.length === 0 ? (
        <p className="text-sm text-zinc-500">No interview transcript captured for this agent.</p>
      ) : (
        <div className="space-y-3">
          {bubbles.map((m) => {
            const isAgent = m.role === 'agent'
            return (
              <div key={m.id} className={`flex gap-2 ${isAgent ? '' : 'flex-row-reverse'}`}>
                <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-white/10 bg-white/5 text-base">
                  {isAgent ? agent.emoji : '🧑'}
                </div>
                <div
                  className={`max-w-[85%] rounded-2xl px-3 py-2 text-sm leading-relaxed ${
                    isAgent
                      ? 'bg-violet-500/10 border border-violet-300/15 text-zinc-200'
                      : 'bg-white/[0.04] border border-white/10 text-zinc-300'
                  }`}
                >
                  <p className="text-[10px] font-semibold uppercase tracking-wider opacity-50 mb-1">
                    {isAgent ? agent.name : 'Founder'}
                  </p>
                  <p className="whitespace-pre-wrap">{m.content}</p>
                </div>
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}

function EmptyState({ title, body }: { title: string; body: string }) {
  const router = useRouter()
  return (
    <div className="glass p-8 border border-white/10 text-center max-w-xl mx-auto">
      <h2 className="text-2xl font-bold text-zinc-100">{title}</h2>
      <p className="text-sm text-zinc-500 leading-relaxed mt-3">{body}</p>
      <Button onClick={() => router.push('/')} className="mt-6">
        Back to SolBorn
      </Button>
    </div>
  )
}
