'use client'

import { Fragment, useEffect, useMemo, useState, type FormEvent } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { Activity, ArrowLeft, Check, ExternalLink, Loader2, Lock, Pencil, Rocket, Send, Share2, ShieldCheck, Sparkles } from 'lucide-react'
import { useSolanaSigner } from '@/lib/hooks/useSolanaSigner'
import { Button } from '@/components/ui/button'
import { WalletButton } from '@/components/wallet/WalletButton'
import { TipButton } from '@/components/agent/TipButton'
import { EditProductModal } from '@/components/agent/EditProductModal'
import { GenerateLandingModal } from '@/components/agent/GenerateLandingModal'
import { GenerateThreadModal } from '@/components/agent/GenerateThreadModal'
import { RenderedLanding } from '@/components/agent/RenderedLanding'
import { useForgeStore } from '@/lib/store'
import { STAGE_CONFIG } from '@/lib/constants'
import type { AgentStage, ForgeAgent, GeneratedProject } from '@/lib/types'

const STAGE_JOURNEY: Array<{ stage: AgentStage; emoji: string }> = [
  { stage: 'baby', emoji: '👶' },
  { stage: 'toddler', emoji: '🧒' },
  { stage: 'teen', emoji: '🧑‍💻' },
  { stage: 'adult', emoji: '🚀' },
]

const TRAIT_FIELDS: Array<{ key: keyof ForgeAgent['traits']; label: string; gradient: string }> = [
  { key: 'curiosity', label: 'Curiosity', gradient: 'from-violet-400 to-fuchsia-300' },
  { key: 'solanaKnowledge', label: 'Solana Knowledge', gradient: 'from-emerald-400 to-teal-300' },
  { key: 'codingSkill', label: 'Coding Skill', gradient: 'from-cyan-400 to-sky-300' },
  { key: 'creativity', label: 'Creativity', gradient: 'from-amber-400 to-orange-300' },
  { key: 'founderMindset', label: 'Founder Mindset', gradient: 'from-rose-400 to-pink-300' },
]

function shortHash(hash: string): string {
  return `${hash.slice(0, 8)}...${hash.slice(-8)}`
}

export default function ProductPage() {
  const router = useRouter()
  const params = useParams<{ id: string }>()
  const agents = useForgeStore((s) => s.agents)
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
  }, [])

  const productId = String(params?.id ?? '')
  const match = useMemo(
    () => agents.find((agent) => agent.generatedProject?.id === productId),
    [agents, productId],
  )
  const agent = match ?? null
  const project = match?.generatedProject ?? null

  return (
    <main className="min-h-screen px-6 py-6">
      <div className="max-w-6xl mx-auto">
        <header className="flex items-center gap-3 mb-8 flex-wrap">
          <Button variant="ghost" size="sm" onClick={() => router.push('/')}>
            <ArrowLeft size={16} />
          </Button>
          <img
            src="/logo.png"
            alt="SolBorn"
            className="w-8 h-8 rounded-xl cursor-pointer"
            onClick={() => router.push('/')}
          />
          <div className="flex-1 min-w-44">
            <h1 className="text-2xl font-bold text-zinc-100">SolBorn Product Page</h1>
            <p className="text-sm text-zinc-500">Generated from a founder interview</p>
          </div>
          <Button variant="secondary" size="sm" onClick={() => router.push('/staking')}>
            $SBORN access
          </Button>
          <Button variant="secondary" size="sm" onClick={() => router.push('/products')}>
            Arena
          </Button>
        </header>

        {!mounted ? (
          <EmptyState title="Loading product..." body="Reading your local SolBorn launch data." />
        ) : !project || !agent ? (
          <EmptyState
            title="Product not found in this browser"
            body="This v1 page reads the product generated by your local agent. Generate a project from an Adult agent first, then open its Product Page link."
          />
        ) : (
          <ProductContent project={project} agent={agent} />
        )}
      </div>
    </main>
  )
}

function ProductContent({
  project,
  agent,
}: {
  project: GeneratedProject
  agent: ForgeAgent
}) {
  const { publicKey } = useSolanaSigner()
  const brief = project.brief
  const agentName = agent.name
  const agentStage = agent.stage
  const [contact, setContact] = useState('')
  const [useCase, setUseCase] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [result, setResult] = useState<{ ok: boolean; message: string } | null>(null)
  const [editOpen, setEditOpen] = useState(false)
  const [generateOpen, setGenerateOpen] = useState(false)
  const [threadOpen, setThreadOpen] = useState(false)
  const updateGeneratedProject = useForgeStore((s) => s.updateGeneratedProject)
  const canSubmit = contact.trim().length >= 3 && useCase.trim().length >= 20
  const walletAddress = publicKey?.toBase58() ?? null
  // Local-store ownership: this product page only renders when the project
  // exists in THIS browser's zustand store. If we got here, the visitor is
  // the local owner — wallet match is meaningful only for on-chain ops.
  // Edits write to local storage; "Generate landing" needs a wallet because
  // it pays 0.05 SOL on mainnet, but that gate lives below.
  const canEdit = true
  const walletConnected = Boolean(walletAddress)
  const accentColor = STAGE_CONFIG[agentStage]?.color ?? '#8b5cf6'
  const hasLanding = Boolean(project.landingContent)
  const hasThread = Boolean(project.launchThread)

  const artworkUrl = useMemo(() => {
    const params = new URLSearchParams({
      kind: 'launch',
      id: agent.id,
      n: agent.name,
      s: agent.stage,
      p: agent.personality,
      xp: String(agent.xp),
      proj: project.name,
      pid: project.id,
    })
    return `/api/nft-metadata/og?${params.toString()}`
  }, [agent.id, agent.name, agent.stage, agent.personality, agent.xp, project.name, project.id])

  const shareUrl = useMemo(() => {
    const text = `${project.name} — launched with @solborn_xyz, the AI memecoin launchpad on Solana. Lore, landing, and thread all generated by the agent.`
    const pageUrl = typeof window !== 'undefined'
      ? window.location.href
      : `https://solborn.xyz/products/${project.id}`
    const params = new URLSearchParams({ text, url: pageUrl })
    return `https://twitter.com/intent/tweet?${params.toString()}`
  }, [project.name, project.id])

  function scrollToRequestAccess() {
    document.getElementById('request-access')?.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }

  async function submitInterest(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    if (!canSubmit || submitting) return
    setSubmitting(true)
    setResult(null)
    try {
      const res = await fetch('/api/products/interest', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          productId: project.id,
          productName: project.name,
          agentName,
          contact: contact.trim(),
          useCase: useCase.trim(),
          wallet: publicKey?.toBase58() ?? null,
        }),
      })
      const data = (await res.json()) as { ok?: boolean; message?: string; error?: string }
      if (!res.ok || !data.ok) {
        throw new Error(data.error ?? 'Request failed')
      }
      setResult({ ok: true, message: data.message ?? 'Request received.' })
      setContact('')
      setUseCase('')
    } catch (error) {
      setResult({
        ok: false,
        message: error instanceof Error ? error.message : 'Request failed',
      })
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="space-y-5">
      <section className="grid lg:grid-cols-[1.15fr_0.85fr] gap-5 items-start">
        <div className="glass p-7 border border-white/10 relative overflow-hidden">
          <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-emerald-300/50 to-transparent" />
          <div className="inline-flex items-center px-3 py-1 rounded-full border border-emerald-300/25 bg-emerald-300/10 text-[11px] font-semibold text-emerald-200 mb-5">
            Agent-built product
          </div>
          <div className="flex items-baseline gap-2 mb-3 flex-wrap">
            <h2 className="text-4xl sm:text-5xl font-bold tracking-tight text-zinc-100">
              {project.name}
            </h2>
            {project.customizedAt && (
              <span
                className="inline-flex items-center gap-1 text-[10px] uppercase tracking-wider text-zinc-500"
                title={`Edited by creator on ${new Date(project.customizedAt).toLocaleDateString()}`}
              >
                <Pencil size={10} />
                edited
              </span>
            )}
          </div>
          {project.tagline && (
            <p className="text-lg sm:text-xl text-zinc-200 leading-snug max-w-3xl mb-4">
              {project.tagline}
            </p>
          )}
          <p className="text-zinc-400 leading-relaxed max-w-3xl">
            {project.description}
          </p>
          <div className="flex flex-wrap gap-2 mt-5">
            {project.productUrl ? (
              <a
                href={project.productUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 rounded-xl px-4 py-2 text-sm font-semibold text-white transition-colors"
                style={{
                  background: `linear-gradient(135deg, ${accentColor}, ${accentColor}cc)`,
                }}
                title={
                  project.productUrlVerified
                    ? 'Verified by Google Safe Browsing'
                    : 'Link not verified — open at your own risk'
                }
              >
                Visit product
                <ExternalLink size={14} />
                {project.productUrlVerified && (
                  <ShieldCheck size={14} className="text-emerald-200" />
                )}
              </a>
            ) : (
              <button
                onClick={scrollToRequestAccess}
                className="inline-flex items-center gap-2 rounded-xl bg-violet-500 px-4 py-2 text-sm font-semibold text-white hover:bg-violet-400 transition-colors"
              >
                Request beta access
              </button>
            )}
            {project.txHash && (
              <a
                href={`https://explorer.solana.com/tx/${project.txHash}?cluster=devnet`}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.03] px-4 py-2 text-sm font-semibold text-zinc-200 hover:bg-white/[0.06] transition-colors"
              >
                <ExternalLink size={14} />
                View launch proof
              </a>
            )}
            <a
              href={shareUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.03] px-4 py-2 text-sm font-semibold text-zinc-200 hover:bg-white/[0.06] transition-colors"
            >
              <Share2 size={14} />
              Share on X
            </a>
            <TipButton
              recipientWallet={agent.walletAddress}
              projectId={project.id}
              projectName={project.name}
            />
            {canEdit && (
              <button
                onClick={() => setEditOpen(true)}
                className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.03] px-4 py-2 text-sm font-semibold text-zinc-200 hover:bg-white/[0.06] transition-colors"
                title="Edit name, tagline, brief, and product link"
              >
                <Pencil size={14} />
                Edit page
              </button>
            )}
            {canEdit && (
              <button
                onClick={() => setGenerateOpen(true)}
                className="inline-flex items-center gap-2 rounded-xl px-4 py-2 text-sm font-semibold text-white transition-colors"
                style={{
                  background: `linear-gradient(135deg, ${accentColor}, ${accentColor}cc)`,
                }}
                title={
                  hasLanding
                    ? 'Regenerate the full landing page'
                    : 'Generate a full landing page from your brief'
                }
              >
                <Sparkles size={14} />
                {hasLanding ? 'Regenerate landing' : 'Generate landing'}
              </button>
            )}
            {canEdit && (
              <button
                onClick={() => setThreadOpen(true)}
                className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.03] px-4 py-2 text-sm font-semibold text-zinc-200 hover:bg-white/[0.06] transition-colors"
                title={
                  hasThread
                    ? 'Open your launch thread'
                    : 'Generate a 7-tweet launch thread from your brief'
                }
              >
                <Sparkles size={14} />
                {hasThread ? 'View launch thread' : 'Generate launch thread'}
              </button>
            )}
          </div>
          <div className="flex flex-wrap gap-2 mt-6">
            {project.techStack.map((tech) => (
              <span
                key={tech}
                className="text-xs px-2.5 py-1 rounded-md bg-white/5 border border-white/10 text-zinc-400"
              >
                {tech}
              </span>
            ))}
          </div>
        </div>

        <div className="glass p-6 border border-white/10">
          <div className="flex items-center gap-2 mb-5">
            <Rocket size={17} className="text-amber-300" />
            <h3 className="text-sm font-semibold text-zinc-100">Launch status</h3>
            {project.txHash && (
              <span className="ml-auto inline-flex items-center gap-1.5 rounded-full border border-emerald-300/25 bg-emerald-300/10 px-2 py-0.5 text-[9px] font-semibold uppercase tracking-wider text-emerald-200">
                <span className="relative flex h-1.5 w-1.5">
                  <span className="absolute inset-0 animate-ping rounded-full bg-emerald-300 opacity-75" />
                  <span className="relative h-1.5 w-1.5 rounded-full bg-emerald-300" />
                </span>
                Verified
              </span>
            )}
          </div>
          {project.txHash ? (
            <a
              href={`https://explorer.solana.com/tx/${project.txHash}?cluster=devnet`}
              target="_blank"
              rel="noopener noreferrer"
              aria-label="Verify launch certificate on Solana Explorer"
              className="group relative block aspect-square w-full overflow-hidden rounded-xl border border-white/10 bg-black/30 mb-5 transition-all duration-300 hover:scale-[1.015] hover:border-emerald-300/40 hover:shadow-[0_0_50px_-8px_rgba(52,211,153,0.45)]"
            >
              <img
                src={artworkUrl}
                alt={`${project.name} Launch Certificate`}
                className="absolute inset-0 h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.04]"
                loading="lazy"
              />
              <div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent opacity-0 transition-opacity duration-300 group-hover:opacity-100" />
              <div className="absolute bottom-2 left-2 inline-flex items-center gap-1 rounded-md border border-white/10 bg-black/60 px-2 py-1 text-[10px] font-mono uppercase tracking-wider text-zinc-300 backdrop-blur">
                <ShieldCheck size={10} className="text-emerald-300" />
                Launch Certificate
              </div>
              <div className="absolute bottom-2 right-2 inline-flex translate-y-1 items-center gap-1 rounded-md border border-emerald-300/30 bg-emerald-300/10 px-2 py-1 text-[10px] font-mono uppercase tracking-wider text-emerald-200 opacity-0 backdrop-blur transition-all duration-300 group-hover:translate-y-0 group-hover:opacity-100">
                <ExternalLink size={10} />
                Verify on-chain
              </div>
            </a>
          ) : (
            <div className="relative aspect-square w-full overflow-hidden rounded-xl border border-white/10 bg-black/30 mb-5">
              <img
                src={artworkUrl}
                alt={`${project.name} Launch Certificate preview`}
                className="absolute inset-0 h-full w-full object-cover opacity-70"
                loading="lazy"
              />
              <div className="absolute bottom-2 left-2 inline-flex items-center gap-1 rounded-md border border-white/10 bg-black/60 px-2 py-1 text-[10px] font-mono uppercase tracking-wider text-zinc-300 backdrop-blur">
                <ShieldCheck size={10} className="text-amber-300" />
                Pending mint
              </div>
            </div>
          )}
          <div className="space-y-3">
            <StatusLine label="Founder agent" value={agentName} />
            <StatusLine label="Stage" value={agentStage} />
            <StatusLine label="Product page" value="Ready" />
            <StatusLine label="Network" value="Solana devnet" />
          </div>
          <div className="grid grid-cols-2 gap-2 mt-5">
            <MiniSignal label="Proof" value={project.txHash ? 'Live' : 'Pending'} />
            <MiniSignal label="Access" value="Waitlist" />
          </div>
          {project.txHash ? (
            <a
              href={`https://explorer.solana.com/tx/${project.txHash}?cluster=devnet`}
              target="_blank"
              rel="noopener noreferrer"
              className="mt-5 flex items-center justify-center gap-1.5 rounded-lg px-3 py-2 text-xs font-medium bg-emerald-300 text-zinc-950 hover:bg-emerald-200 transition-colors"
            >
              <ExternalLink size={12} />
              View certificate {shortHash(project.txHash)}
            </a>
          ) : (
            <div className="mt-5 rounded-lg border border-amber-300/20 bg-amber-300/10 px-3 py-2 text-xs text-amber-100">
              Publish the Launch Certificate to attach on-chain proof.
            </div>
          )}
        </div>
      </section>

      {project.landingContent && (
        <RenderedLanding landing={project.landingContent} accentColor={accentColor} />
      )}

      <section className="grid lg:grid-cols-[0.92fr_1.08fr] gap-5">
        <AgentIdCard agent={agent} />
        <FounderProfile agent={agent} />
      </section>

      <section className="grid lg:grid-cols-[0.92fr_1.08fr] gap-5">
        <div className="glass p-6 border border-white/10">
          <div className="flex items-center gap-2 mb-5">
            <Lock size={17} className="text-violet-300" />
            <h3 className="text-sm font-semibold text-zinc-100">Beta Access</h3>
          </div>
          <h4 className="text-2xl font-bold text-zinc-100">
            Get on the early access list
          </h4>
          <p className="text-sm text-zinc-500 mt-2">
            Free during the build phase. Tell us how you&apos;d use it. We hand-pick first users.
          </p>

          <div className="mt-5 space-y-2 rounded-xl border border-violet-300/15 bg-violet-400/[0.04] p-4">
            <p className="text-xs font-semibold uppercase tracking-wider text-violet-200">
              What happens next
            </p>
            <div className="space-y-2 text-sm text-zinc-300">
              <StepRow index="01" text="You send a serious beta request with your use case." />
              <StepRow index="02" text="We review fit manually instead of blasting open access." />
              <StepRow index="03" text="If it matches, the founder reaches out directly on your contact." />
            </div>
          </div>

          <form id="request-access" onSubmit={submitInterest} className="mt-5 space-y-3 border-t border-white/10 pt-5">
            <div className="flex items-center justify-between gap-3">
              <div>
                <p className="text-xs font-semibold uppercase tracking-wider text-zinc-500">
                  Request beta access
                </p>
                <p className="text-xs text-zinc-600 mt-1">Tell us how you would use it. We want early users, not vanity signups.</p>
              </div>
              <WalletButton />
            </div>
            <input
              value={contact}
              onChange={(event) => setContact(event.target.value)}
              placeholder="X / Telegram / email"
              className="w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-zinc-100 placeholder:text-zinc-700 focus:outline-none focus:border-violet-300/60"
              maxLength={120}
            />
            <textarea
              value={useCase}
              onChange={(event) => setUseCase(event.target.value)}
              placeholder="What are you building, and how would you use this product? Be specific."
              className="min-h-24 w-full resize-none rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-zinc-100 placeholder:text-zinc-700 focus:outline-none focus:border-violet-300/60"
              maxLength={700}
            />
            <p className="text-[10px] text-zinc-600">{useCase.length}/700 · min 20 chars</p>
            <Button
              type="submit"
              disabled={!canSubmit || submitting}
              className="w-full bg-white text-zinc-950 hover:bg-zinc-200"
            >
              {submitting ? <Loader2 size={15} className="animate-spin" /> : result?.ok ? <Check size={15} /> : <Send size={15} />}
              {submitting ? 'Sending...' : result?.ok ? 'Request sent' : 'Request beta access'}
            </Button>
            {result && (
              <p className={`text-xs leading-relaxed ${result.ok ? 'text-emerald-300' : 'text-rose-300'}`}>
                {result.message}
              </p>
            )}
          </form>
        </div>

        <div className="glass p-6 border border-white/10">
          <div className="flex items-center gap-2 mb-5">
            <ShieldCheck size={17} className="text-emerald-300" />
            <h3 className="text-sm font-semibold text-zinc-100">Product Brief</h3>
          </div>
          <div className="grid sm:grid-cols-2 gap-3">
            <BriefBlock label="Target user" value={brief?.targetUser} />
            <BriefBlock label="Problem" value={brief?.problem} />
            <BriefBlock label="Solution" value={brief?.solution} />
            <BriefBlock label="MVP" value={brief?.mvp} />
            <BriefBlock label="Solana angle" value={brief?.solanaAngle} />
            <BriefBlock label="Pricing" value={brief?.pricing} />
          </div>
          <div className="mt-5">
            <p className="text-xs font-semibold uppercase tracking-wider text-zinc-500 mb-3">
              Launch plan
            </p>
            <div className="space-y-2">
              {(brief?.launchPlan ?? ['Generate product page', 'Publish certificate', 'Invite early users']).map((step, index) => (
                <div
                  key={step}
                  className="flex items-start gap-3 rounded-lg border border-white/10 bg-white/[0.03] px-3 py-2 text-sm text-zinc-300"
                >
                  <span className="text-[10px] font-bold text-emerald-300 mt-0.5">{index + 1}</span>
                  <span>{step}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {editOpen && (
        <EditProductModal
          project={project}
          agent={agent}
          agentId={agent.id}
          onClose={() => setEditOpen(false)}
          accentColor={accentColor}
        />
      )}

      {generateOpen && (
        <GenerateLandingModal
          agent={agent}
          project={project}
          accentColor={accentColor}
          onClose={() => setGenerateOpen(false)}
          onSuccess={(landing) => {
            updateGeneratedProject(agent.id, { landingContent: landing })
            setGenerateOpen(false)
          }}
        />
      )}

      {threadOpen && (
        <GenerateThreadModal
          agent={agent}
          project={project}
          accentColor={accentColor}
          onClose={() => setThreadOpen(false)}
          onSuccess={(thread) => {
            updateGeneratedProject(agent.id, { launchThread: thread })
          }}
        />
      )}
    </div>
  )
}

function MiniSignal({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-white/10 bg-white/[0.03] px-3 py-2">
      <p className="text-[10px] uppercase tracking-wider text-zinc-600">{label}</p>
      <p className="text-sm font-semibold text-zinc-100 mt-1">{value}</p>
    </div>
  )
}

function StepRow({ index, text }: { index: string; text: string }) {
  return (
    <div className="flex items-start gap-3 rounded-lg border border-white/10 bg-black/20 px-3 py-2">
      <span className="mt-0.5 text-[10px] font-mono text-violet-300">{index}</span>
      <span>{text}</span>
    </div>
  )
}

function BriefBlock({ label, value }: { label: string; value?: string }) {
  return (
    <div className="rounded-lg border border-white/10 bg-white/[0.03] p-4">
      <p className="text-[10px] uppercase tracking-wider text-zinc-600">{label}</p>
      <p className="text-sm text-zinc-300 leading-relaxed mt-2">{value ?? 'Defined by the agent during generation.'}</p>
    </div>
  )
}

function StatusLine({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between gap-3 rounded-lg border border-white/10 bg-white/[0.03] px-3 py-2">
      <span className="text-xs text-zinc-600">{label}</span>
      <span className="text-xs text-zinc-200 text-right capitalize">{value}</span>
    </div>
  )
}

function AnimatedBar({ value, gradient }: { value: number; gradient: string }) {
  const target = Math.max(0, Math.min(100, value))
  const [width, setWidth] = useState(0)
  useEffect(() => {
    const t = setTimeout(() => setWidth(target), 90)
    return () => clearTimeout(t)
  }, [target])
  return (
    <div className="h-1.5 w-full overflow-hidden rounded-full bg-white/[0.05]">
      <div
        className={`h-full rounded-full bg-gradient-to-r ${gradient} transition-[width] duration-1000 ease-out`}
        style={{ width: `${width}%` }}
      />
    </div>
  )
}

function AgentIdCard({ agent }: { agent: ForgeAgent }) {
  const xpPct = Math.min(100, Math.round((agent.xp / Math.max(1, agent.xp + agent.xpToNext)) * 100))
  const stageIndex = STAGE_JOURNEY.findIndex((s) => s.stage === agent.stage)
  return (
    <div className="glass p-6 border border-white/10 relative overflow-hidden">
      <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-violet-300/40 to-transparent" />
      <div className="flex items-center gap-2 mb-5">
        <Sparkles size={17} className="text-violet-300" />
        <h3 className="text-sm font-semibold text-zinc-100">Founder Agent</h3>
      </div>
      <div className="flex items-center gap-4">
        <div className="relative flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl border border-white/10 bg-gradient-to-br from-violet-500/25 to-emerald-300/15 text-4xl shadow-[0_0_30px_-8px_rgba(167,139,250,0.45)]">
          {agent.emoji}
          <div className="absolute -bottom-1 -right-1 inline-flex items-center justify-center rounded-full border border-emerald-300/30 bg-zinc-950/90 px-1.5 py-0.5 text-[9px] font-mono uppercase tracking-wider text-emerald-300 backdrop-blur">
            {agent.stage}
          </div>
        </div>
        <div className="min-w-0">
          <p className="truncate text-lg font-bold text-zinc-100">{agent.name}</p>
          <p className="text-xs text-zinc-500 capitalize">{agent.personality}</p>
        </div>
      </div>

      <div className="mt-5 flex items-center justify-between gap-1">
        {STAGE_JOURNEY.map((s, i) => {
          const reached = i <= stageIndex
          const current = i === stageIndex
          return (
            <Fragment key={s.stage}>
              <div className="flex flex-col items-center gap-1">
                <span
                  className={`text-lg leading-none transition-all duration-500 ${
                    current ? 'opacity-100 scale-110 drop-shadow-[0_0_8px_rgba(167,139,250,0.6)]' : reached ? 'opacity-70' : 'opacity-25 grayscale'
                  }`}
                >
                  {s.emoji}
                </span>
                <span
                  className={`text-[8px] font-mono uppercase tracking-wider ${
                    current ? 'text-violet-200' : 'text-zinc-700'
                  }`}
                >
                  {s.stage}
                </span>
              </div>
              {i < STAGE_JOURNEY.length - 1 && (
                <div
                  className={`mb-3 h-px flex-1 ${
                    i < stageIndex ? 'bg-gradient-to-r from-violet-400/60 to-emerald-300/40' : 'bg-white/[0.06]'
                  }`}
                />
              )}
            </Fragment>
          )
        })}
      </div>

      <div className="mt-5 space-y-2">
        <div className="flex items-center justify-between text-[11px]">
          <span className="uppercase tracking-wider text-zinc-600">XP</span>
          <span className="font-mono text-zinc-300">{agent.xp.toLocaleString()} <span className="text-zinc-700">/ {(agent.xp + agent.xpToNext).toLocaleString()}</span></span>
        </div>
        <AnimatedBar value={xpPct} gradient="from-violet-400 to-emerald-300" />
      </div>

      <a
        href={`/forge/${agent.id}`}
        className="mt-5 inline-flex items-center gap-1.5 text-xs font-semibold text-violet-300 hover:text-violet-200 transition-colors"
      >
        Open agent <ExternalLink size={11} />
      </a>
    </div>
  )
}

function FounderProfile({ agent }: { agent: ForgeAgent }) {
  const ageDays = Math.max(1, Math.round((Date.now() - agent.createdAt) / 86400000))
  const totalScore = TRAIT_FIELDS.reduce((sum, t) => sum + (agent.traits?.[t.key] ?? 0), 0)
  return (
    <div className="glass p-6 border border-white/10 relative overflow-hidden">
      <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-emerald-300/40 to-transparent" />
      <div className="flex items-center gap-2 mb-5">
        <Activity size={17} className="text-emerald-300" />
        <h3 className="text-sm font-semibold text-zinc-100">Founder Profile</h3>
        <span className="ml-auto text-[9px] uppercase tracking-wider text-zinc-600">measured during interview</span>
      </div>

      <div className="space-y-3">
        {TRAIT_FIELDS.map((t) => {
          const value = agent.traits?.[t.key] ?? 0
          return (
            <div key={t.key}>
              <div className="flex items-center justify-between text-[11px] mb-1">
                <span className="text-zinc-400">{t.label}</span>
                <span className="font-mono text-zinc-300">{value}<span className="text-zinc-700">/100</span></span>
              </div>
              <AnimatedBar value={value} gradient={t.gradient} />
            </div>
          )
        })}
      </div>

      <div className="mt-5 grid grid-cols-3 gap-2 border-t border-white/10 pt-4">
        <ProfileStat label="Score" value={totalScore.toString()} accent="text-emerald-300" />
        <ProfileStat label="Interactions" value={agent.totalInteractions.toString()} />
        <ProfileStat label="Days alive" value={ageDays.toString()} />
      </div>
    </div>
  )
}

function ProfileStat({ label, value, accent }: { label: string; value: string; accent?: string }) {
  return (
    <div>
      <p className="text-[9px] uppercase tracking-wider text-zinc-600">{label}</p>
      <p className={`text-sm font-bold mt-1 truncate ${accent ?? 'text-zinc-200'}`}>{value}</p>
    </div>
  )
}

function EmptyState({ title, body }: { title: string; body: string }) {
  const router = useRouter()
  return (
    <div className="glass p-8 border border-white/10 text-center max-w-xl mx-auto">
      <h2 className="text-2xl font-bold text-zinc-100">{title}</h2>
      <p className="text-sm text-zinc-500 leading-relaxed mt-3">{body}</p>
      <Button onClick={() => router.push('/')} className="mt-6">
        Back to SolBorn
      </Button>
    </div>
  )
}
